### PR TITLE
Add initial docs

### PR DESCRIPTION
**Pull request by HammerMeetNail**
This change is [Reviewable](https://reviewable.io/reviews/cratekube/cloud-mgmt-service/2)

### CODE REVIEW

**Comment by danielfoglio** [comment]
@kod4n Signoff?

**Comment by HammerMeetNail** [comment]
yeah, for sure

**Comment by HammerMeetNail** [comment]
___
*[.gitignore, line 21 at r1](https://reviewable.io/reviews/cratekube/cloud-mgmt-service/2#-M1gWmv31HHWuUPpYzPS:-M1hE7x96c7Sf-2GQJNj:b-465g72) ([raw file](https://github.com/cratekube/cloud-mgmt-service/blob/b03ab13ffd74b5c3c492eb8e002313d4465655f2/.gitignore#L21)):*
<details><summary><i>Previously, kod4n (Andrew Allen) wrote…</i></summary><blockquote>

Do you think we will need subdirectories under `docs/` at some point?  Adding `!docs/**/*` should help future proof that going forward.
</blockquote></details>

I'm not sure we're even going to need docs in the future. I was thinking the directory was only temporary until we settled on whether to use pages or readthedocs. Any issues revisiting this following that decision?

**Comment by HammerMeetNail** [comment]
:lgtm:

**Pull request merged**
